version: '3'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-gold
    depends_on:
    - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080

  firefox:
    image: selenium/node-firefox:3.141.59-gold
    depends_on:
    - hub
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080

  hub:
    image: selenium/hub:3.141.59-gold
    ports:
    - "4444:4444"